CREATE TABLE IF NOT EXISTS `zoomos_pricelist`
(
    `id`             int(11)                                 NOT NULL,
    `shopmanager_id` int(11)                                 DEFAULT NULL,
    `model`          varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `quantity`       int(11)                                 NOT NULL,
    `price`          double(8, 2)                            NOT NULL,
    `slug`           varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `status`         smallint(6)                             NOT NULL,
    `is_new`         smallint(6)                             NOT NULL,
    `image`          varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `vendor_id`      int(11)                                 NOT NULL,
    `vendor_name`    varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `category_id`    int(11)                                 NOT NULL,
    `category_name`  varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `category_slug`  varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `item_date_add`  int(11)                                 NOT NULL,
    `item_date_upd`  int(11)                                 NOT NULL,
    `created_at`     timestamp                               NOT NULL DEFAULT '0000-00-00 00:00:00',
    `updated_at`     timestamp                               NOT NULL DEFAULT '0000-00-00 00:00:00',
    `f8631_id`       int(11)                                          DEFAULT NULL COMMENT 'Сезонность ID',
    `f8631_val`      smallint(6)                                      DEFAULT NULL COMMENT 'Сезонность',
    `f8632_id`       int(11)                                          DEFAULT NULL COMMENT 'Шипы ID',
    `f8632_val`      tinyint(1)                                       DEFAULT NULL COMMENT 'Шипы',
    `f8633_id`       int(11)                                          DEFAULT NULL COMMENT 'Тип автомобиля ID',
    `f8633_val`      varchar(255) COLLATE utf8mb4_unicode_ci          DEFAULT NULL COMMENT 'Тип автомобиля',
    `f8628_id`       int(11)                                          DEFAULT NULL COMMENT 'Ширина ID',
    `f8628_val`      smallint(6)                                      DEFAULT NULL COMMENT 'Ширина',
    `f8629_id`       int(11)                                          DEFAULT NULL COMMENT 'Высота ID',
    `f8629_val`      smallint(6)                                      DEFAULT NULL COMMENT 'Высота',
    `f8630_id`       int(11)                                          DEFAULT NULL COMMENT 'Диаметр ID',
    `f8630_val`      smallint(6)                                      DEFAULT NULL COMMENT 'Диаметр',
    `f8637_id`       int(11)                                          DEFAULT NULL COMMENT 'Индекс нагрузки ID',
    `f8637_val`      smallint(6)                                      DEFAULT NULL COMMENT 'Индекс нагрузки',
    `f8638_id`       int(11)                                          DEFAULT NULL COMMENT 'Максимальная нагрузка ID',
    `f8638_val`      smallint(6)                                      DEFAULT NULL COMMENT 'Макс. нагрузка (на одну шину)',
    `f8639_id`       int(11)                                          DEFAULT NULL COMMENT 'Индекс макс. скорости ID',
    `f8639_val`      varchar(255) COLLATE utf8mb4_unicode_ci          DEFAULT NULL COMMENT 'Индекс макс. скорости',
    `f8634_id`       int(11)                                          DEFAULT NULL COMMENT 'Конструкция ID',
    `f8634_val`      varchar(255) COLLATE utf8mb4_unicode_ci          DEFAULT NULL COMMENT 'Конструкция',
    `f8635_id`       int(11)                                          DEFAULT NULL COMMENT 'Технология RunFlat ID',
    `f8635_val`      tinyint(1)                                       DEFAULT NULL COMMENT 'Технология RunFlat',
    `f8636_id`       int(11)                                          DEFAULT NULL COMMENT 'Способ герметизации ID',
    `f8636_val`      varchar(255) COLLATE utf8mb4_unicode_ci          DEFAULT NULL COMMENT 'Способ герметизации'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
